#!/bin/sh
set -e

# 1. Session secret. lib/tasks/initializers.rake writes config/initializers/secret_token.rb.
# Prefer REDMINE_SECRET_KEY_BASE env (same file on all replicas if load-balanced),
# else generate once and persist via the tmp/ or plugins/ volume.
if [ ! -f config/initializers/secret_token.rb ]; then
  if [ -n "$REDMINE_SECRET_KEY_BASE" ]; then
    cat > config/initializers/secret_token.rb <<EOF
# frozen_string_literal: true
# Generated by docker-entrypoint from REDMINE_SECRET_KEY_BASE.
RedmineApp::Application.config.secret_key_base = '$REDMINE_SECRET_KEY_BASE'
EOF
    echo "Wrote secret_token.rb from REDMINE_SECRET_KEY_BASE"
  else
    bundle exec rake generate_secret_token
    echo "Generated secret_token.rb (persist it via volume for multi-replica setups)"
  fi
fi

# 2. config/database.yml. Prefer mounted file; else generate it.
# NOTE: this file must ALWAYS exist before any `bundle exec` call, even when
# DATABASE_URL is set. Gemfile:58-97 declares DB gems (mysql2/pg/sqlite3) based
# on the adapter found here — with no file, `bundle exec` excludes mysql2 from
# the bundle and Rails dies with `Gem::LoadError: mysql2 is not part of the
# bundle`. Rails still takes host/user/pass/db from DATABASE_URL when both exist.
if [ ! -s config/database.yml ]; then
  if [ -n "$DATABASE_URL" ]; then
    case "$DATABASE_URL" in
      mysql2://*)    URL_ADAPTER=mysql2 ;;
      trilogy://*)   URL_ADAPTER=trilogy ;;
      postgresql://*|postgres://*) URL_ADAPTER=postgresql ;;
      sqlite3:*)     URL_ADAPTER=sqlite3 ;;
      sqlserver://*) URL_ADAPTER=sqlserver ;;
      *) echo "Cannot parse adapter from DATABASE_URL=$DATABASE_URL" >&2; exit 1 ;;
    esac
    if [ "$URL_ADAPTER" = "sqlite3" ]; then
      URL_DB=$(echo "$DATABASE_URL" | sed -E 's|^sqlite3:(.*?)(\?.*)?$|\1|')
      printf 'production:\n  adapter: sqlite3\n  database: "%s"\n' "$URL_DB" > config/database.yml
    else
      URL_DB=$(echo "$DATABASE_URL" | sed -E 's|^[a-z0-9+]+://[^/]*/([^?]+).*|\1|')
      cat > config/database.yml <<EOF
production:
  adapter: $URL_ADAPTER
  database: ${URL_DB:-redmine}
  encoding: utf8mb4
EOF
    fi
    echo "Wrote config/database.yml (adapter=$URL_ADAPTER) from DATABASE_URL; connection still comes from DATABASE_URL"
  else
    : "${REDMINE_DB_ADAPTER:=mysql2}"
    : "${REDMINE_DB_HOST:=db}"
    : "${REDMINE_DB_PORT:=3306}"
    : "${REDMINE_DB_NAME:=redmine}"
    : "${REDMINE_DB_USER:=redmine}"
    : "${REDMINE_DB_PASS:=redmine}"
    cat > config/database.yml <<EOF
production:
  adapter: $REDMINE_DB_ADAPTER
  database: $REDMINE_DB_NAME
  host: $REDMINE_DB_HOST
  port: $REDMINE_DB_PORT
  username: $REDMINE_DB_USER
  password: "$REDMINE_DB_PASS"
  encoding: utf8mb4
  variables:
    transaction_isolation: "READ-COMMITTED"
EOF
    echo "Wrote config/database.yml for $REDMINE_DB_ADAPTER@$REDMINE_DB_HOST"
  fi
fi

# 3. Wait for TCP DB (mysql/pg only; sqlite needs nothing).
if [ -z "$DATABASE_URL" ]; then
  DB_HOST=$(grep -A5 '^production:' config/database.yml | grep -i host: | awk '{print $2}' | tr -d '"')
else
  case "$DATABASE_URL" in
    *mysql*|*trilogy*) DB_HOST=$(echo "$DATABASE_URL" | sed -E 's|.*@([^:/]+).*|\1|') ;;
    *postgres*) DB_HOST=$(echo "$DATABASE_URL" | sed -E 's|.*@([^:/]+).*|\1|') ;;
    *) DB_HOST="" ;;
  esac
fi
if [ -n "$DB_HOST" ] && [ "$DB_HOST" != "localhost" ]; then
  DB_PORT=3306
  echo "$DATABASE_URL" | grep -q postgres && DB_PORT=5432
  grep -q port: config/database.yml 2>/dev/null && DB_PORT=$(grep -A8 '^production:' config/database.yml | grep port: | awk '{print $2}' | head -1)
  echo "Waiting for DB $DB_HOST:$DB_PORT ..."
  for i in $(seq 1 60); do
    (echo > /dev/tcp/"$DB_HOST"/"$DB_PORT") >/dev/null 2>&1 && break
    sleep 2
  done
fi

# 4. Migrate (doc/INSTALL step 7). Creates tables + admin/admin on fresh DB.
bundle exec rails db:migrate

# 5. Enforce ownership when volumes are mounted as root.
chown -R redmine:redmine files log tmp public/assets 2>/dev/null || true

exec "$@"
